// examples/react/src/app/tyform-example.tsx
import { string, builder as tyform } from "tyform";
import { Button, Form, Input, Label, Small } from "./tyform-example.style";
import { FormItem } from "packages/form/src/types";
import { useState } from "react";

interface Contact {
  Name: string;
  Phone: string;
  Email: string;
}

function TyInput<T extends string | number | undefined | readonly string[]>( { item }: { item: FormItem<T> }) {
  return <Input
    type="text"
    defaultValue={item.value}
    onInput={e => item.value = (e.target as HTMLInputElement).value as T}
    ></Input>
}

function TyErrors<T>({ item } : { item: FormItem<T>}) {
  const [ errors, setErrors ] = useState(item.error);

  item.subscribe(item => setErrors(item.error))

  return <Small>
    {errors.join(', ')}
  </Small>
}

export function TyFormExample() {
  const phone_rgx = /(\d{2})(\d)(\d{4})(\d{4})/;
  const email_rgx = /([\w_.]+)@(\w+\.\w+)/;

  const builder = tyform<Contact>({
    Name: string()
      .required('Name is required')
      .transform(value => value.toUpperCase()),
    Phone: string()
      .validate(value => phone_rgx.test(value)).withMessage('Phone format is invalid'),
    Email: string()
      .validate(value => email_rgx.test(value)).withMessage('Email format is invalid')
  }).init({
    Name: 'João Miguel',
    Phone: '27998765432',
    Email: 'joao.miguel@hotmail.com'
  })

  const form = builder.build();

  const [invalid, setInvalid] = useState(false);

  builder.subscribe(form => {
    const result = Object.values(form).reduce((acc, cur) => cur.invalid || acc, false);
    setInvalid(result);
  });
  
  const Submit = (e: Event) => {
    e.preventDefault();
    const values = builder.values();
    console.log(values);
  }

  return (
    <Form>
      <Label>
        Name:
        <TyInput item={form.Name}></TyInput>
        <TyErrors item={form.Name}></TyErrors>
      </Label>
      <Label>
        Phone:
        <TyInput item={form.Phone}></TyInput>
        <TyErrors item={form.Phone}></TyErrors>
      </Label>
      <Label>
        Email:
        <TyInput item={form.Email}></TyInput>
        <TyErrors item={form.Email}></TyErrors>
      </Label>
      <Button disabled={invalid} onClick={ev => Submit(ev.nativeEvent)}>Submit</Button>
    </Form>
  );
}

export default TyFormExample;

// examples/angular/src/app/tyform-example.ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { builder as tyform, string } from 'tyform'
import { Form, FormBuilder } from 'packages/form/src/types';

@Component({
  selector: 'tyform-example',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <style>

      :root {
        --error-color: rgb(255, 75, 75);
      }

      form {
        display: flex;
        flex-direction: column;

        gap: 10px;

        max-width: 500px;
        width: 500px;
      }

      form label {
        display: flex;
        flex-direction: column;
      }

      form label input {
        margin-top: 5px;
      }

      form label input.invalid {
        border: 0.1em solid var(--error-color);
      }

      form label small {
        color: var(--error-color);
      }

      form button {
        width: fit-content;
      }
    </style>

    <form>
      <label>
        Name:
        <input [class.invalid]="form.Name.invalid" name="Name" [(ngModel)]="form.Name.value" type="text"/>
        <small>{{form.Name.error.join(', ')}}</small>
      </label>
      <label>
        Phone:
        <input [class.invalid]="form.Phone.invalid" name="Phone" [(ngModel)]="form.Phone.value" type="text"/>
        <small>{{form.Phone.error.join(', ')}}</small>
      </label>
      <label>
        Email:
        <input [class.invalid]="form.Email.invalid" name="Email" [(ngModel)]="form.Email.value" type="text"/>
        <small>{{form.Email.error.join(', ')}}</small>
      </label>
      <button [disabled]="isFormInvalid" (click)="submit()">Submit</button>
    </form>
  `,
  styles: [],
  encapsulation: ViewEncapsulation.None,
})
export class TyformExampleComponent implements OnInit {
  public readonly PHONE_RGX = /(\d{2})(\d)(\d{4})(\d{4})/;
  public readonly EMAIL_RGX = /([\w_.]+)@(\w+\.\w+)/;

  private buider!: FormBuilder<Contact>;
  public form!: Form<Contact>;

  public get isFormInvalid() {
    return Object.values(this.form).reduce((acc, cur) => cur.invalid || acc, false)
  }

  ngOnInit(): void {

    this.buider = tyform<Contact>({
      Name: string()
        .required("Name is required"),
      Phone: string()
        .validate(value => this.PHONE_RGX.test(value)).withMessage('Phone format is invalid'),
      Email: string()
        .validate(value => this.EMAIL_RGX.test(value)).withMessage('Email format is invalid')
    }).init({
      Name: 'João Miguel',
      Phone: '27998765432',
      Email: 'jao.miguel@hotmail.com'
    })

    this.form = this.buider.build();
  }

  submit() {
    const values = this.buider.values();
    console.log(values)
  }
}

interface Contact {
  Name: string;
  Phone: string;
  Email: string;
}
